name: Rust

on:
  push:
    branches: 
      - 'main'
      - 'releases/**'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'

env:
  CARGO_TERM_COLOR: always
  # RUSTFLAGS: "-Dwarnings"

jobs:
  build-test:
    name: Build Rust Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      
  test:
    name: Test Rust Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test --verbose
  
  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --all-targets --all-features
