name: Rust

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build & Test Rust Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose
      
    - name: Test
      run: cargo test --verbose
